# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  hardware.cpu.intel.updateMicrocode = true;

  boot = {
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [];
    initrd = {
      availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [];
      supportedFilesystems = [ "btrfs" ];
      luks = {
        reusePassphrases = true;
        devices = {
          "king120ga" = {
            device = "/dev/disk/by-uuid/d289c688-38fc-434e-a8ea-899ebf18a413";
            allowDiscards = true;
            fallbackToPassword = true;
            keyFile = "/dev/disk/by-uuid/no-such-uuid";
            keyFileSize = 2048;
          };

          "king120gb" = {
            device = "/dev/disk/by-uuid/550dd120-9025-427f-b8b2-aff5cc9af18b";
            allowDiscards = true;
            fallbackToPassword = true;
            keyFile = "/dev/disk/by-uuid/no-such-uuid";
            keyFileSize = 2048;
          };
        };
      };

    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/king120ga";
      fsType = "btrfs";
      options = [ "subvol=@root" "ssd" "compress=zstd" ];
    };

    "/.snapshots" = {
      device = "/dev/mapper/king120ga";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "ssd" "compress=zstd" ];
    };

    "/nix" = {
      device = "/dev/mapper/king120ga";
      fsType = "btrfs";
      options = [ "subvol=@nix" "ssd" "compress=zstd" ];
    };

    "/home" = {
      device = "/dev/mapper/king120ga";
      fsType = "btrfs";
      options = [ "subvol=@home" "ssd" "compress=zstd" ];
    };

    "/persist" = {
      device = "/dev/mapper/king120ga";
      fsType = "btrfs";
      options = [ "subvol=@persist" "ssd" "compress=zstd" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/4C2C-8603";
      fsType = "vfat";
    };

    "/data" = {
      device = "/dev/disk/by-uuid/9fbbc081-5aec-4553-95dd-cf33f5727c28";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };
  };

  swapDevices = [];

  services = {
    fstrim.enable = true;
    btrfs.autoScrub = {
      enable = true;
      fileSystems = [ "/" "/data" ];
    };
    smartd = {
      enable = true;
      defaults.autodetected = "-a -o on -s (S/../.././02|L/../../7/04)";
    };
  };
  #services.beesd.filesystems = {
  #        data = {
  #          spec = "UUID=9fbbc081-5aec-4553-95dd-cf33f5727c28";
  #        };
  #        data = {
  #          spec = "UUID=ac583763-282e-4845-b7b6-f28fe39ce72e";
  #        };
  #};

  nix.maxJobs = lib.mkDefault 4;
}
