## DO NOT EDIT THIS FILE
## It is automatically generated by terraform.
[
  {
    # cube.denys.me
    publicKey = "9z01LiXRxCMWQrCi7vh88kASdYvexrpcx9xbktX7elQ=";
    allowedIPs = [ "10.100.0.4/32" ];
  }
  {
    # laptop
    publicKey = "MOX+q35dIXuUNzZlEReZr7NLsuARVUoPgBl78SAQdU4=";
    allowedIPs = [ "10.100.0.2/32" ];
  }
  {
    # phone
    publicKey = "CnmO5cGmqu6kAMMZwhdCi85oln+PqVfd/3N4OlGrilI=";
    allowedIPs = [ "10.100.0.3/32" ];
  }
]
